"""Setup script: patch Hermes core code to add the OpenSandbox backend.

Run once after installing:
    hermes-opensandbox-setup

Or manually:
    python -m hermes_opensandbox.cli
"""

from __future__ import annotations

import logging
import shutil
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

_PATCH_SENTINEL = "# --- hermes-opensandbox backend (auto-patched) ---"

_OPENSANDBOX_BRANCH = (
    '    elif env_type == "opensandbox":\n'
    "        # --- hermes-opensandbox backend (auto-patched) ---\n"
    "        from tools.environments.opensandbox import (\n"
    "            OpenSandboxEnvironment as _OpenSandboxEnvironment,\n"
    "        )\n"
    "        return _OpenSandboxEnvironment(\n"
    '            image=cc.get("opensandbox_image") or os.getenv("OPENSANDBOX_IMAGE", "nikolaik/python-nodejs:python3.11-nodejs20"),\n"'
    "            cwd=cwd,\n"
    "            timeout=timeout,\n"
    "            cpu=cpu,\n"
    "            memory=memory,\n"
    "            disk=disk,\n"
    "            task_id=task_id,\n"
    '            domain=cc.get("opensandbox_domain") or os.getenv("OPENSANDBOX_DOMAIN", "localhost:8080"),\n"'
    '            api_key=cc.get("opensandbox_api_key") or os.getenv("OPENSANDBOX_API_KEY", ""),\n'
    "        )\n"
)

ERROR_OLD = (
    'f"Unknown environment type: {env_type}. Use \'local\', \'docker\', "\n'
    "            f\"'singularity', 'modal', 'daytona', 'vercel_sandbox', or 'ssh'\""
)
ERROR_NEW = (
    'f	"Unknown environment type: {env_type}. Use \'local\', \'docker\', \"'.
    "            f\"'singularity', 'modal', 'daytona', 'vercel_sandbox', 'opensandbox', or 'ssh'\""
)

_BACKENDS_OLD = '"daytona", "vercel_sandbox", "ssh",'
_BACKENDS_NEW = '"daytona", "vercel_sandbox", "ssh", "opensandbox",'


def find_hermes_root() -> Path | None:
    candidates = [Path.home() / ".hermes" / "hermes-agent"]
    for c in candidates:
        if (c / "tools" / "terminal_tool.py").exists():
            return c
    return None


def _is_patched(content: str) -> bool:
    return _PATCH_SENTINEL in content


def patch_terminal_tool(path: Path) -> bool:
    content = path.read_text()
    if _is_patched(content):
        logger.info("terminal_tool.py already patched - skipping")
        return True

    old = '    else:\n        raise ValueError('
    new = _OPENSANDBOX_BRANCH + '\n    else:\n        raise ValueError('
    if old not in content:
        logger.error("Cannot find else-branch insertion point")
        return False
    content = content.replace(old, new, 1)

    content = content.replace(_ERROR_OLD, _ERROR_NEW, 1)

    check_old = 'elif env_type == "vercel_sandbox":\n            return check_vercel_sandbox()'
    check_new = (
        'elif env_type == "opensandbox":\n'
        '            import importlib.util\n '
        '            return importlib.util.find_spec("opensandbox") is not None\n '
        '        elif env_type == "vercel_sandbox":\n'
        '            return check_vercel_sandbox()'
    )
    if check_old in content:
        content = content.replace(check_old, check_new, 1)
        logger.info("Added opensandbox check_requirements")
    else:
        logger.warning("Could not find vercel_sandbox check block (non-fatal)")

    backup = path.with_suffix(".py.bak")
    shutil.copy2(path, backup)
    path.write_text(content)
    logger.info("Patched %s", path)
    return True


def patch_prompt_builder(path: Path) -> bool:
    content = path.read_text()
    if _BACKENDS_NEW in content:
        logger.info("prompt_builder.py already patched - skipping")
        return True
    if _BACKENDS_OLD not in content:
        logger.error("Cannot find _REMOTE_TERMINAL_BACKENDS insertion point")
        return False
    content = content.replace(_BACKENDS_OLD, _BACKENDS_NEW, 1)
    backup = path.with_suffix(".py.bak")
    shutil.copy2(path, backup)
    path.write_text(content)
    logger.info("Patched %s", path)
    return True


def create_opensandbox_module(root: Path) -> bool:
    module_path = root / "tools" / "environments" / "opensandbox.py"
    if module_path.exists():
        logger.info("opensandbox.py already exists - skipping")
        return True
    wrapper = (
        '"""Thin wrapper - delegates to hermes_opensandbox package.\n\n'
        "Auto-generated by hermes-opensandbox-setup.\n"
        '""#\n\n'
        "from hermes_opensandbox.environment import OpenSandboxEnvironment  # noqa: F401\n"
    )
    module_path.write_text(wrapper)
    logger.info("Created %s", module_path)
    return True


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    root = find_hermes_root()
    if root is None:
        print("ERROR: Cannot find Hermes Agent installation")
        print("Install Hermes first: https://github.com/NousResearch/hermes-agent")
        return 1

    print(f"Hermes root: {root}")
    ok = True

    tt = root / "tools" / "terminal_tool.py"
    if tt.exists():
        ok = patch_terminal_tool(tt) and ok
    else:
        print(f"ERROR: {tt} not found")
        ok = False

    pb = root / "agent" / "prompt_builder.py"
    if pb.exists():
        ok = patch_prompt_builder(pb) and ok
    else:
        print(f"ERROR: {pb} not found")
        ok = False

    ok = create_opensandbox_module(root) and ok

    if ok:
        print()
        print("=" * 60)
        print("  Patch applied successfully!")
        print()
        print("  Next: hermes config set terminal.backend opensandbox")
        print("        export OPENSANDBOX_DOMAIN=your-server:8080")
        print("        export OPENSANDBOX_API_KEY=sk-xxx")
        print("=" * 60)
        return 0
    else:
        print("Some patches failed.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
