"""Setup script: patch Hermes core code to register the OpenSandbox backend.

Run once after installing:

    hermes-open-sandbox-setup

Or manually:

    python -m hermes_opensandbox.cli

All patches are idempotent — safe to run multiple times.
"""

from __future__ import annotations

import logging
import re
import shutil
import sys
from pathlib import Path

from importlib.metadata import version as pkg_version

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Version-tagged sentinel — embedded in every auto-patched block so
# we can detect stale injections and replace them on upgrade.
# ------------------------------------------------------------------

_PATCH_VERSION = pkg_version("hermes-open-sandbox")
_SENTINEL_RE = re.compile(
    r"# --- hermes-opensandbox backend (?:v([\d.]+) )?\(auto-patched\) ---"
)
_LEGACY_SENTINEL = "# --- hermes-opensandbox backend (auto-patched) ---"
_SENTINEL = f"# --- hermes-opensandbox backend v{_PATCH_VERSION} (auto-patched) ---"

# ------------------------------------------------------------------
# Injection-point markers (used for detection & replacement)
# ------------------------------------------------------------------

_TERMINAL_TOOL = "terminal_tool.py"
_PROMPT_BUILDER = "prompt_builder.py"
_ADAPTER_MODULE = "opensandbox.py"

# frozenset marker — we insert BEFORE the closing "})"
_RTB_MARKER = ' "vercel_sandbox",'

# _BACKEND_FALLBACK_DESCRIPTIONS marker
_BFD_MARKER = '"ssh": "a remote host reached over SSH (likely Linux)",'

# else: raise ValueError(...) block in _create_environment — single match/replace
_ELSE_MARKER = """    else:
        raise ValueError(
            f"Unknown environment type: {env_type}. Use 'local', 'docker', "
            f"'singularity', 'modal', 'daytona', 'vercel_sandbox', or 'ssh'"
        )"""

# check_vercel_sandbox guard in check_environment_requirements() —
# we insert opensandbox check before it.  Regex matches the elif-line
# followed by ``return <any_func>(config)`` so minor renames in Hermes
# Agent won't silently break the injection.
_CHECK_PATTERN = re.compile(
    r'elif env_type == "vercel_sandbox":\n\s+return\s+\w+\(config\)'
)
_OPEN_CHECK_STANZA = (
    'elif env_type == "opensandbox":\n'
    "            import importlib.util\n"
    '            return importlib.util.find_spec("opensandbox") is not None\n'
    "        "
)

_OPEN_BRANCH_PATTERN = re.compile(
    r'    elif env_type == "opensandbox":\n'
    r"        # --- hermes-opensandbox backend (?:v[\d.]+ )?\(auto-patched\) ---\n"
    r".*?"
    r"        \)\n",
    re.DOTALL,
)


# ------------------------------------------------------------------
# Thin adapter template  (written into tools/environments/opensandbox.py)
# ------------------------------------------------------------------

_ADAPTER_CODE = '''"""Thin adapter — delegates to the hermes_opensandbox package.

Auto-generated by hermes-open-sandbox-setup.  Do not edit manually.
"""

{_sentinel}

import shlex
import os
import threading
from datetime import timedelta

from tools.environments.base import BaseEnvironment, _ThreadedProcessHandle
from hermes_opensandbox.session import OpenSandboxSession, SandboxCreationError
from hermes_opensandbox.config import SandboxConfig


_RENEW_INTERVAL = 600


def _is_debug() -> bool:
    return os.getenv("OPENSANDBOX_DEBUG", "") in ("1", "true", "yes")


class OpenSandboxEnvironment(BaseEnvironment):
    """OpenSandbox execution backend for Hermes Agent.

    One sandbox is created per session and persists across all commands.
    A background thread periodically renews the sandbox expiration so it
    stays alive for the entire session lifetime.
    """

    _stdin_mode = "heredoc"

    def __init__(  # noqa: PLR0913
        self,
        image: str,
        cwd: str,
        timeout: int,
        cpu: float,
        memory: int,
        disk: int,
        task_id: str,
        domain: str,
        api_key: str,
        mounts: dict[str, str] | None = None,
        volumes: list[dict] | None = None,
    ) -> None:
        super().__init__(cwd=cwd, timeout=timeout)

        self._config = SandboxConfig(
            image=image,
            domain=domain,
            api_key=api_key,
            cwd=cwd,
            timeout=timeout,
            cpu=cpu,
            memory=memory,
            disk=disk,
            task_id=task_id,
            mounts=mounts,
            volumes=volumes,
            debug=_is_debug(),
        )
        self._session = OpenSandboxSession(self._config)
        self._lock = threading.Lock()
        self._stop_renew = threading.Event()

        try:
            self._session.create()
        except SandboxCreationError:
            raise

        self._renew_thread = threading.Thread(target=self._renew_loop, daemon=True)
        self._renew_thread.start()
        self.init_session()

    # --------------------------------------------------------------
    # Renewal
    # --------------------------------------------------------------

    def _renew_loop(self) -> None:
        try:
            with self._lock:
                self._session.renew()
            logger.debug("Initial sandbox renewal successful")
        except Exception:
            logger.warning("Initial sandbox renewal failed", exc_info=True)
        
        while not self._stop_renew.wait(_RENEW_INTERVAL):
            try:
                with self._lock:
                    self._session.renew()
                logger.debug("Sandbox renewed successfully")
            except Exception:
                logger.warning("Sandbox renewal failed, will retry in %ds", _RENEW_INTERVAL, exc_info=True)

    def _ensure_sandbox(self) -> None:
        """Recreate the sandbox if it was killed (e.g. by cancel)."""
        with self._lock:
            if not self._session.is_alive():
                self._session.create()

    # --------------------------------------------------------------
    # BaseEnvironment interface
    # --------------------------------------------------------------

    def _run_bash(
        self,
        cmd_string: str,
        *,
        login: bool = False,
        timeout: int = 120,
        stdin_data: str | None = None,
    ) -> _ThreadedProcessHandle:
        del timeout  # sandbox has its own timeout via config
        del stdin_data  # heredoc mode — already embedded by base class

        if login:
            cmd_string = f"bash -l -c {{shlex.quote(cmd_string)}}"

        self._ensure_sandbox()

        session = self._session

        def _exec() -> tuple[str, int]:
            return session.execute(cmd_string)

        def _cancel() -> None:
            pass  # sandbox persists across commands; thread result is discarded

        return _ThreadedProcessHandle(exec_fn=_exec, cancel_fn=_cancel)

    def cleanup(self) -> None:
        self._stop_renew.set()
        self._session.kill()
        self._session.close()
'''.format(_sentinel=_SENTINEL)

# ------------------------------------------------------------------
# _create_environment elif branch (inserted before "else: raise ValueError")
# ------------------------------------------------------------------

_OPEN_BRANCH = f"""    elif env_type == "opensandbox":
        {_SENTINEL}
        from tools.environments.opensandbox import (
            OpenSandboxEnvironment as _OpenSandboxEnvironment,
        )
        from hermes_opensandbox.config import SandboxConfig as _SandboxConfig
        _sandbox_cfg = _SandboxConfig.from_env()
        return _OpenSandboxEnvironment(
            image=_sandbox_cfg.image,
            cwd=cwd,
            timeout=_sandbox_cfg.timeout,
            cpu=_sandbox_cfg.cpu,
            memory=_sandbox_cfg.memory,
            disk=_sandbox_cfg.disk,
            task_id=task_id,
            domain=_sandbox_cfg.domain,
            api_key=_sandbox_cfg.api_key,
            mounts=_sandbox_cfg.mounts,
            volumes=_sandbox_cfg.volumes,
        )
"""

_ELSE_REPLACEMENT = (
    _OPEN_BRANCH
    + """    else:
        raise ValueError(
            f"Unknown environment type: {env_type}. Use 'local', 'docker', "
            f"'singularity', 'modal', 'daytona', 'vercel_sandbox', 'opensandbox', or 'ssh'"
        )"""
)


# ------------------------------------------------------------------
#  Helpers
# ------------------------------------------------------------------


def find_hermes_root() -> Path | None:
    """Locate the Hermes Agent installation directory."""
    candidates = [Path.home() / ".hermes" / "hermes-agent"]
    for c in candidates:
        if (c / "tools" / _TERMINAL_TOOL).exists():
            return c
    return None


def _extract_patch_version(content: str) -> str | None:
    """Return the version string embedded in a prior sentinel, or ``None``."""
    m = _SENTINEL_RE.search(content)
    return m.group(1) if m else None


# ------------------------------------------------------------------
#  Patchers
# ------------------------------------------------------------------


def patch_terminal_tool(path: Path) -> bool:
    """Insert opensandbox branch + update error message in terminal_tool.py.

    Each injection point is checked independently so partial patches
    (e.g. a prior version that only applied step 1) are completed on
    re-run rather than skipped wholesale.

    When the opensandbox branch already exists, the embedded version is
    compared with the current package version.  If they differ the
    entire block is replaced with the latest template so parameter
    additions (e.g. ``volumes``) are always propagated.
    """
    content = path.read_text()
    changed = False

    # 1. Replace or insert the opensandbox elif branch in _create_environment.
    existing_ver = _extract_patch_version(content)
    has_legacy = _LEGACY_SENTINEL in content
    if existing_ver is not None or has_legacy:
        if existing_ver != _PATCH_VERSION:
            match = _OPEN_BRANCH_PATTERN.search(content)
            if match:
                content = (
                    content[: match.start()] + _OPEN_BRANCH + content[match.end() :]
                )
                changed = True
                logger.info(
                    "Patched terminal_tool.py: updated opensandbox branch %s → v%s",
                    f"v{existing_ver}" if existing_ver else "legacy",
                    _PATCH_VERSION,
                )
            else:
                logger.warning(
                    "terminal_tool.py: sentinel found but block could not be matched; "
                    "skipping update"
                )
        else:
            logger.info(
                "terminal_tool.py: opensandbox branch v%s already up-to-date",
                existing_ver,
            )
    elif _ELSE_MARKER in content:
        content = content.replace(_ELSE_MARKER, _ELSE_REPLACEMENT, 1)
        changed = True
        logger.info(
            "Patched terminal_tool.py: inserted opensandbox branch v%s + updated error message",
            _PATCH_VERSION,
        )
    else:
        logger.error("Cannot find else-block insertion point in terminal_tool.py")
        return False

    # 2. Insert opensandbox stanza in check_environment_requirements()
    #    (regex-based so minor renames in Hermes Agent don't silently fail)
    if 'find_spec("opensandbox")' in content:
        logger.info("terminal_tool.py: opensandbox check_requirements already present")
    elif _CHECK_PATTERN.search(content):
        content = _CHECK_PATTERN.sub(
            lambda m: _OPEN_CHECK_STANZA + m.group(0), content, count=1
        )
        changed = True
        logger.info("Patched terminal_tool.py: added opensandbox requirement check")
    else:
        logger.warning(
            "Could not match requirement-check insertion point in terminal_tool.py "
            "(non-fatal — Hermes Agent may have changed structure)"
        )

    if not changed:
        return True

    _backup_and_write(path, content)
    return True


def patch_prompt_builder(path: Path) -> bool:
    """Add 'opensandbox' to _REMOTE_TERMINAL_BACKENDS and fallback descriptions."""
    content = path.read_text()

    already = '"opensandbox"' in content
    existing_ver = _extract_patch_version(content)
    has_legacy = _LEGACY_SENTINEL in content

    if already and existing_ver == _PATCH_VERSION and not has_legacy:
        logger.info(
            "prompt_builder.py already patched at v%s, skipping", _PATCH_VERSION
        )
        return True

    changed = False

    # 1. Add to _REMOTE_TERMINAL_BACKENDS frozenset
    if _RTB_MARKER in content:
        # Insert after "vercel_sandbox", in the frozenset
        new_rtb = f'{_RTB_MARKER}\n        "opensandbox",'
        if _RTB_MARKER in content and new_rtb not in content:
            content = content.replace(_RTB_MARKER, new_rtb, 1)
            changed = True
            logger.info(
                "Patched prompt_builder.py: added opensandbox to _REMOTE_TERMINAL_BACKENDS"
            )
    else:
        logger.warning("Could not find _REMOTE_TERMINAL_BACKENDS insertion point")

    # 2. Add fallback description
    fallback_entry = '\n    "opensandbox": "an OpenSandbox container (Linux)",'
    if _BFD_MARKER in content and fallback_entry not in content:
        replacement = _BFD_MARKER + fallback_entry
        content = content.replace(_BFD_MARKER, replacement, 1)
        changed = True
        logger.info("Patched prompt_builder.py: added opensandbox fallback description")
    elif fallback_entry in content:
        pass  # already done
    else:
        logger.warning("Could not find _BACKEND_FALLBACK_DESCRIPTIONS insertion point")

    if not changed:
        return True

    _backup_and_write(path, content)
    return True


def create_opensandbox_module(root: Path) -> bool:
    """Create or update the thin adapter ``tools/environments/opensandbox.py``.

    Always overwrites auto-generated files so the latest template is deployed.
    """
    module_path = root / "tools" / "environments" / _ADAPTER_MODULE
    if module_path.exists():
        current = module_path.read_text()
        if _LEGACY_SENTINEL in current or _SENTINEL_RE.search(current):
            existing_ver = _extract_patch_version(current)
            if existing_ver != _PATCH_VERSION:
                module_path.write_text(_ADAPTER_CODE)
                logger.info(
                    "opensandbox.py updated %s → v%s",
                    f"v{existing_ver}" if existing_ver else "legacy",
                    _PATCH_VERSION,
                )
            else:
                logger.info("opensandbox.py already at v%s, skipping", _PATCH_VERSION)
            return True
        logger.warning(
            "opensandbox.py exists but was NOT auto-generated — skipping to avoid overwrite"
        )
        return True

    module_path.write_text(_ADAPTER_CODE)
    logger.info("Created %s (v%s)", module_path, _PATCH_VERSION)
    return True


# ------------------------------------------------------------------
#  Helpers
# ------------------------------------------------------------------


def _backup_and_write(path: Path, content: str) -> None:
    backup = path.with_suffix(".py.bak")
    try:
        if backup.exists():
            backup.unlink()
        shutil.copy2(path, backup)
        logger.info("Backup saved to %s", backup)
    except PermissionError:
        logger.warning(
            "Cannot create backup %s (permission denied), writing without backup",
            backup,
        )
    path.write_text(content)


# ------------------------------------------------------------------
#  Entry point
# ------------------------------------------------------------------


def main() -> int:
    """Patch Hermes to register the opensandbox backend (idempotent)."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    root = find_hermes_root()
    if root is None:
        logger.error(
            "Hermes Agent installation not found. Expected at ~/.hermes/hermes-agent/"
        )
        return 1

    ok = True

    # 1 & 2. Patch terminal_tool.py (branch insertion + error message)
    tt = root / "tools" / _TERMINAL_TOOL
    if tt.exists():
        ok = patch_terminal_tool(tt) and ok
    else:
        logger.warning("terminal_tool.py not found, skipping")

    # 3 & 4. Patch prompt_builder.py (backends frozenset + descriptions)
    pb = root / "agent" / _PROMPT_BUILDER
    if pb.exists():
        ok = patch_prompt_builder(pb) and ok
    else:
        logger.warning("prompt_builder.py not found, skipping")

    # 5. Create thin adapter module
    ok = create_opensandbox_module(root) and ok

    if ok:
        logger.info("hermes-open-sandbox setup complete (v%s)", _PATCH_VERSION)
        return 0

    return 1


if __name__ == "__main__":
    sys.exit(main())
