"""Setup script: patch Hermes core code to register the OpenSandbox backend.

Run once after installing:

    hermes-opensandbox-setup

Or manually:

    python -m hermes_opensandbox.cli

All patches are idempotent — safe to run multiple times.
"""

from __future__ import annotations

import logging
import shutil
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Sentinel — marks all auto-patched / auto-generated code
# ------------------------------------------------------------------

_SENTINEL = "# --- hermes-opensandbox backend (auto-patched) ---"

# ------------------------------------------------------------------
# Injection-point markers (used for detection & replacement)
# ------------------------------------------------------------------

_TERMINAL_TOOL = "terminal_tool.py"
_PROMPT_BUILDER = "prompt_builder.py"
_ADAPTER_MODULE = "opensandbox.py"

# frozenset marker — we insert BEFORE the closing "})"
_RTB_MARKER = ' "vercel_sandbox",'

# _BACKEND_FALLBACK_DESCRIPTIONS marker
_BFD_MARKER = '"ssh": "a remote host reached over SSH (likely Linux)",'

# else: raise ValueError(...) block in _create_environment — single match/replace
_ELSE_MARKER = '''    else:
        raise ValueError(
            f"Unknown environment type: {env_type}. Use 'local', 'docker', "
            f"'singularity', 'modal', 'daytona', 'vercel_sandbox', or 'ssh'"
        )'''

# check_vercel_sandbox guard — we insert opensandbox check before it
_CHECK_MARKER = 'elif env_type == "vercel_sandbox":\n            return check_vercel_sandbox()'

_CHECK_REPLACEMENT = (
    'elif env_type == "opensandbox":\n'
    "            import importlib.util\n"
    "            return importlib.util.find_spec("
    '"opensandbox") is not None\n'
    '        elif env_type == "vercel_sandbox":\n'
    "            return check_vercel_sandbox()"
)


# ------------------------------------------------------------------
# Thin adapter template  (written into tools/environments/opensandbox.py)
# ------------------------------------------------------------------

_ADAPTER_CODE = '''"""Thin adapter — delegates to the hermes_opensandbox package.

Auto-generated by hermes-opensandbox-setup.  Do not edit manually.
"""

{_sentinel}

import shlex

from tools.environments.base import BaseEnvironment, _ThreadedProcessHandle
from hermes_opensandbox.session import OpenSandboxSession, SandboxCreationError
from hermes_opensandbox.config import SandboxConfig


class OpenSandboxEnvironment(BaseEnvironment):
    """OpenSandbox execution backend for Hermes Agent."""

    _stdin_mode = "heredoc"

    def __init__(  # noqa: PLR0913
        self,
        image: str,
        cwd: str,
        timeout: int,
        cpu: float,
        memory: int,
        disk: int,
        task_id: str,
        domain: str,
        api_key: str,
    ) -> None:
        super().__init__(cwd=cwd, timeout=timeout)

        self._config = SandboxConfig(
            image=image,
            domain=domain,
            api_key=api_key,
            cwd=cwd,
            timeout=timeout,
            cpu=cpu,
            memory=memory,
            disk=disk,
            task_id=task_id,
        )
        self._session = OpenSandboxSession(self._config)
        try:
            self._session.create()
        except SandboxCreationError:
            raise
        self.init_session()

    # --------------------------------------------------------------
    # BaseEnvironment interface
    # --------------------------------------------------------------

    def _run_bash(
        self,
        cmd_string: str,
        *,
        login: bool = False,
        timeout: int = 120,
        stdin_data: str | None = None,
    ) -> _ThreadedProcessHandle:
        del timeout  # sandbox has its own timeout via config
        del stdin_data  # heredoc mode — already embedded by base class

        if login:
            cmd_string = f"bash -l -c {{shlex.quote(cmd_string)}}"

        session = self._session

        def _exec() -> tuple[str, int]:
            return session.execute(cmd_string)

        def _cancel() -> None:
            session.kill()

        return _ThreadedProcessHandle(exec_fn=_exec, cancel_fn=_cancel)

    def cleanup(self) -> None:
        self._session.kill()
        self._session.close()
'''.format(_sentinel=_SENTINEL)

# ------------------------------------------------------------------
# _create_environment elif branch (inserted before "else: raise ValueError")
# ------------------------------------------------------------------

_OPEN_BRANCH = f'''    elif env_type == "opensandbox":
        {_SENTINEL}
        from tools.environments.opensandbox import (
            OpenSandboxEnvironment as _OpenSandboxEnvironment,
        )
        from hermes_opensandbox.config import SandboxConfig as _SandboxConfig
        _sandbox_cfg = _SandboxConfig.from_env(
            image=cc.get("opensandbox_image"),
            domain=cc.get("opensandbox_domain"),
            api_key=cc.get("opensandbox_api_key"),
        )
        return _OpenSandboxEnvironment(
            image=_sandbox_cfg.image,
            cwd=cwd,
            timeout=timeout,
            cpu=cpu,
            memory=memory,
            disk=disk,
            task_id=task_id,
            domain=_sandbox_cfg.domain,
            api_key=_sandbox_cfg.api_key,
        )
'''

_ELSE_REPLACEMENT = _OPEN_BRANCH + '''    else:
        raise ValueError(
            f"Unknown environment type: {env_type}. Use 'local', 'docker', "
            f"'singularity', 'modal', 'daytona', 'vercel_sandbox', 'opensandbox', or 'ssh'"
        )'''


# ------------------------------------------------------------------
#  Helpers
# ------------------------------------------------------------------


def find_hermes_root() -> Path | None:
    """Locate the Hermes Agent installation directory."""
    candidates = [Path.home() / ".hermes" / "hermes-agent"]
    for c in candidates:
        if (c / "tools" / _TERMINAL_TOOL).exists():
            return c
    return None


def _is_patched(content: str) -> bool:
    return _SENTINEL in content


# ------------------------------------------------------------------
#  Patchers
# ------------------------------------------------------------------


def patch_terminal_tool(path: Path) -> bool:
    """Insert opensandbox branch + update error message in terminal_tool.py."""
    content = path.read_text()
    if _is_patched(content):
        logger.info("terminal_tool.py already patched, skipping")
        return True

    changed = False

    # 1. Replace the entire else: block with opensandbox elif + updated else
    if _ELSE_MARKER in content:
        content = content.replace(_ELSE_MARKER, _ELSE_REPLACEMENT, 1)
        changed = True
        logger.info("Patched terminal_tool.py: inserted opensandbox branch + updated error message")
    else:
        logger.error("Cannot find else-block insertion point in terminal_tool.py")
        return False

    # 2. Add opensandbox requirement check
    if _CHECK_MARKER in content:
        content = content.replace(_CHECK_MARKER, _CHECK_REPLACEMENT, 1)
        logger.info("Patched terminal_tool.py: added opensandbox requirement check")
    elif _CHECK_REPLACEMENT in content:
        pass  # already done
    else:
        logger.warning("Could not add opensandbox check_requirements (non-fatal)")

    if not changed:
        return True

    _backup_and_write(path, content)
    return True


def patch_prompt_builder(path: Path) -> bool:
    """Add 'opensandbox' to _REMOTE_TERMINAL_BACKENDS and fallback descriptions."""
    content = path.read_text()

    already = '"opensandbox"' in content
    remote_patched = _is_patched(content)

    if already and remote_patched:
        logger.info("prompt_builder.py already patched, skipping")
        return True

    changed = False

    # 1. Add to _REMOTE_TERMINAL_BACKENDS frozenset
    if _RTB_MARKER in content:
        # Insert after "vercel_sandbox", in the frozenset
        new_rtb = f'{_RTB_MARKER}\n        "opensandbox",'
        if _RTB_MARKER in content and new_rtb not in content:
            content = content.replace(_RTB_MARKER, new_rtb, 1)
            changed = True
            logger.info(
                "Patched prompt_builder.py: added opensandbox to _REMOTE_TERMINAL_BACKENDS"
            )
    else:
        logger.warning("Could not find _REMOTE_TERMINAL_BACKENDS insertion point")

    # 2. Add fallback description
    fallback_entry = '\n    "opensandbox": "an OpenSandbox container (Linux)",'
    if _BFD_MARKER in content and fallback_entry not in content:
        replacement = _BFD_MARKER + fallback_entry
        content = content.replace(_BFD_MARKER, replacement, 1)
        changed = True
        logger.info(
            "Patched prompt_builder.py: added opensandbox fallback description"
        )
    elif fallback_entry in content:
        pass  # already done
    else:
        logger.warning(
            "Could not find _BACKEND_FALLBACK_DESCRIPTIONS insertion point"
        )

    if not changed:
        return True

    _backup_and_write(path, content)
    return True


def create_opensandbox_module(root: Path) -> bool:
    """Create the thin adapter ``tools/environments/opensandbox.py``."""
    module_path = root / "tools" / "environments" / _ADAPTER_MODULE
    if module_path.exists():
        current = module_path.read_text()
        if _SENTINEL in current:
            logger.info("opensandbox.py already exists (auto-generated), skipping")
            return True
        logger.warning(
            "opensandbox.py exists but was NOT auto-generated — skipping to avoid overwrite"
        )
        return True

    module_path.write_text(_ADAPTER_CODE)
    logger.info("Created %s", module_path)
    return True


# ------------------------------------------------------------------
#  Helpers
# ------------------------------------------------------------------


def _backup_and_write(path: Path, content: str) -> None:
    backup = path.with_suffix(".py.bak")
    shutil.copy2(path, backup)
    path.write_text(content)
    logger.info("Backup saved to %s", backup)


# ------------------------------------------------------------------
#  Entry point
# ------------------------------------------------------------------


def main() -> int:
    """Patch Hermes to register the opensandbox backend (idempotent)."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    root = find_hermes_root()
    if root is None:
        logger.error(
            "Hermes Agent installation not found. "
            "Expected at ~/.hermes/hermes-agent/"
        )
        return 1

    ok = True

    # 1 & 2. Patch terminal_tool.py (branch insertion + error message)
    tt = root / "tools" / _TERMINAL_TOOL
    if tt.exists():
        ok = patch_terminal_tool(tt) and ok
    else:
        logger.warning("terminal_tool.py not found, skipping")

    # 3 & 4. Patch prompt_builder.py (backends frozenset + descriptions)
    pb = root / "agent" / _PROMPT_BUILDER
    if pb.exists():
        ok = patch_prompt_builder(pb) and ok
    else:
        logger.warning("prompt_builder.py not found, skipping")

    # 5. Create thin adapter module
    ok = create_opensandbox_module(root) and ok

    if ok:
        logger.info("hermes-opensandbox setup complete")
        return 0

    return 1


if __name__ == "__main__":
    sys.exit(main())
